# Setup
title:               Life In Lo-Fi
tagline:             Ora basta, anarchia!
description:
url:                 https://mrfrost80.github.io
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Mr. Frost
  url:               https://twitter.com/00MrFrost00
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
